glslangValidator -V src/client/shaders/sky.comp.glsl -o res/shaders/sky.comp.spv
glslangValidator -V src/client/shaders/copy.frag.glsl -o res/shaders/copy.frag.spv
glslangValidator -V src/client/shaders/block.vert.glsl -o res/shaders/block.vert.spv
glslangValidator -V src/client/shaders/block.frag.glsl -o res/shaders/block.frag.spv
glslangValidator -V src/client/shaders/water.vert.glsl -o res/shaders/water.vert.spv
glslangValidator -V src/client/shaders/water.frag.glsl -o res/shaders/water.frag.spv
glslangValidator -V src/client/shaders/blockOutline.vert.glsl -o res/shaders/blockOutline.vert.spv
glslangValidator -V src/client/shaders/blockOutline.frag.glsl -o res/shaders/blockOutline.frag.spv
glslangValidator -V src/client/shaders/bloomDownsample.comp.glsl -o res/shaders/bloomDownsample.comp.spv
glslangValidator -V src/client/shaders/bloomUpsample.comp.glsl -o res/shaders/bloomUpsample.comp.spv
glslangValidator -V src/client/shaders/luminance.comp.glsl -o res/shaders/luminance.comp.spv
glslangValidator -V src/client/shaders/fullscreen.vert.glsl -o res/shaders/fullscreen.vert.spv
glslangValidator -V src/client/shaders/toneMap.frag.glsl -o res/shaders/toneMap.frag.spv
glslangValidator --target-env vulkan1.3 src/client/shaders/parallelReduceMean.comp.glsl -o res/shaders/parallelReduceMean.comp.spv
glslangValidator -V src/client/shaders/autoExposure.comp.glsl -o res/shaders/autoExposure.comp.spv
glslangValidator -V src/client/shaders/crosshair.vert.glsl -o res/shaders/crosshair.vert.spv
glslangValidator -V src/client/shaders/crosshair.frag.glsl -o res/shaders/crosshair.frag.spv
glslangValidator -V src/client/shaders/menu.vert.glsl -o res/shaders/menu.vert.spv
glslangValidator -V src/client/shaders/menu.frag.glsl -o res/shaders/menu.frag.spv
glslangValidator -V src/client/shaders/font.vert.glsl -o res/shaders/font.vert.spv
glslangValidator -V src/client/shaders/font.frag.glsl -o res/shaders/font.frag.spv
glslangValidator -V src/client/shaders/fullscreenBlit.frag.glsl -o res/shaders/fullscreenBlit.frag.spv
